name: 'Apply Kernel Branding & Timestamp'
description: 'Apply Wild kernel branding to kernel version string'
inputs:
  variant:
    description: 'Variant of kernel to apply branding to'
    required: true
  kernel_version:
    description: 'Kernel version (e.g., 6.1)'
    required: true
  android_version:
    description: 'Android version (e.g., android14)'
    required: true
  version:
    description: 'Combined version (e.g., android14-6.1)'
    required: true
  sublevel:
    description: 'Sublevel of kernel version (e.g., 1)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply Kernel Name Branding
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        CUSTOM_NAME="@Coolpak@kugouzei_NB_LKM"

        if [[ ${{ inputs.version }} == "android15-6.6" || ${{ inputs.version }} == "android16-6.12" ]]; then
          KERNEL_STRING="${{ inputs.kernel_version }}.${{ inputs.sublevel }}-$CUSTOM_NAME"
          sed -i '$d' scripts/setlocalversion && echo "echo \"$KERNEL_STRING\"" >> scripts/setlocalversion
        else
          sed -i '$d' scripts/setlocalversion && echo "echo \"-$CUSTOM_NAME\"" >> scripts/setlocalversion
        fi
        chmod +x scripts/setlocalversion
